name: Test-and-Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

  defaults:
    run:
      working-directory: noeTaskManager-app.Primary

  steps:
    - uses: actions/checkout@v4
    - name: Setup .Net
      uses: actions/set-up-dotnet@v4
      with:
        dotnet-version: "8.x"
    - name: Install all dependencies
      run: dotnet restore
    - name: Build
      run: dotner build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
